name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Setup python
      run: uv python install
    
    - name: Install dev dependencies
      run: uv sync

    - name: Run tests
      run: uv run pytest

    - name: Check code formatting with Black
      run: uv run ruff check .

    - name: Type check with MyPy
      run: uv run mypy rasper_ducky && uv run mypy tests
